-- MySQL Script generated by MySQL Workbench
-- Wed Sep  1 00:53:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gtsi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gtsi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gtsi` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gtsi` ;

-- -----------------------------------------------------
-- Table `gtsi`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtsi`.`hibernate_sequence` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gtsi`.`panne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtsi`.`panne` (
  `id_panne` INT(11) NOT NULL,
  `date_panne` DATE NULL DEFAULT NULL,
  `adresse_mail` VARCHAR(100) NULL DEFAULT NULL,
  `description` VARCHAR(10000) NULL DEFAULT NULL,
  `id_type` INT(11) NULL DEFAULT NULL,
  `id_reponse` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_panne`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gtsi`.`reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtsi`.`reponse` (
  `id_reponse` INT(11) NOT NULL,
  `date_reponse` DATE NULL DEFAULT NULL,
  `description` VARCHAR(10000) NULL DEFAULT NULL,
  `adresse_mail` VARCHAR(1000) NULL DEFAULT NULL,
  `technicien` VARCHAR(30) NULL DEFAULT NULL,
  `id_panne` INT(11) NULL DEFAULT NULL,
  `id_type` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_reponse`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gtsi`.`type_panne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtsi`.`type_panne` (
  `id_type` INT(11) NOT NULL,
  `type_probleme` VARCHAR(1000) NULL DEFAULT NULL,
  `type_panne` VARCHAR(1000) NULL DEFAULT NULL,
  `type_equipement` VARCHAR(1000) NULL DEFAULT NULL,
  `date` VARCHAR(255) NULL DEFAULT NULL,
  `adresse` VARCHAR(255) NULL DEFAULT NULL,
  `id_panne` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gtsi`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtsi`.`utilisateur` (
  `adresse_mail` VARCHAR(30) NOT NULL,
  `mot_de_passe` VARCHAR(255) NULL DEFAULT NULL,
  `type_utilisateur` VARCHAR(30) NULL DEFAULT NULL,
  `nom` VARCHAR(30) NULL DEFAULT NULL,
  `prenom` VARCHAR(30) NULL DEFAULT NULL,
  `tel` INT(11) NULL DEFAULT NULL,
  `date_de_naissance` DATE NULL DEFAULT NULL,
  `enabled` TINYINT(1) NULL DEFAULT NULL,
  `genre` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`adresse_mail`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
